#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ESPmDNS.h>
#include <Update.h>
#include <Ticker.h>
#include <ESPping.h>
#include <EEPROM.h>
#include "CameraHandler.h"
#include "Log.h"
#include "html.h"
#include <FastLED.h>
#include "Motorbike.h"
#include "Contest.h"